### PR TITLE
Fix `optee` panics when TLS is used

### PR DESCRIPTION
**Pull request by ntauth**
This PR fixes optee panics whenever code that accesses the thread-local storage is used. An example is `HashMap::new()`, which uses an internal `RandomState` struct that stores thread-local keys used by the hasher.

### CODE REVIEW

**Comment by mssun** [comment]
Thanks! @DemesneGH, can you help to review this PR?

**Review by DemesneGH — CHANGES_REQUESTED** [review]
Looks good to me but this line of code should be removed: https://github.com/mesalock-linux/rust/blob/6abda667852184641149d34da4730d96ba4f7d31/library/std/src/sys/optee/mod.rs#L34

**Comment by ntauth** [comment]
> Looks good to me but this line of code should be removed:
> 
> https://github.com/mesalock-linux/rust/blob/6abda667852184641149d34da4730d96ba4f7d31/library/std/src/sys/optee/mod.rs#L34

Well spotted, fixed.

**Review by DemesneGH — APPROVED** [review]
CI checks passed.
Thanks!

**Pull request merged**
